default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: ania
  password: '123'
  
development:
  <<: *default
  database: challenge_development

test:
  <<: *default
  database: challenge_test

production:
  <<: *default
  database: challenge_production